[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Â¿CuÃ¡l de las siguientes operaciones estÃ¡ soportada por el TAD Diccionario, pero no por el TAD Conjunto?
"""
prompt.distractors = [
	"""
`erase` para borrar un elemento o entrada
	""",
	"""
`insert` para aÃ±adir un elemento o entrada
	""",
	"""
`contains` para saber la pertenencia de un elemento o clave
	"""
]
answer.answer = """
`at` para buscar un valor a partir de una clave
"""
id = "51f4933a-fb1e-48be-a66f-a159742a0403"


[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Supongamos que tenemos un objeto de la clase `MapTree<K, V>`. Â¿QuÃ© recibe su mÃ©todo `erase`?
"""
prompt.distractors = [
	"""
Un valor de tipo `MapEntry<K, V>`
	""",
	"""
Un valor de tipo `V`
	"""	
]
answer.answer = """
Un valor de tipo `K`
"""
id = "ab43bbfa-c875-4f9c-8abb-8f10b87d1d78"




[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Supongamos que tenemos un objeto de la clase `MapTree<K, V>`. Â¿QuÃ© recibe su mÃ©todo `insert`?
"""
prompt.distractors = [
	"""
Un valor de tipo `K`
	""",
	"""
Un valor de tipo `V`
	"""	
]
answer.answer = """
Un valor de tipo `MapEntry<K, V>`
"""
id = "8ff6bdfb-0529-4e18-aa55-5afcee4eca29"


[[questions]]
type = "ShortAnswer"
prompt.prompt = """
Supongamos el siguiente cÃ³digo:

```cpp
MapTree<int, int> m;
m.insert({1, 3});
m.insert({1, 5});
```

Â¿QuÃ© devuelve `m.size()` tras ejecutar este cÃ³digo?
"""

answer.answer = "1"

context = """
Al insertar dos elementos con la misma clave, la segunda inserciÃ³n no tiene efecto. Por tanto, el diccionario solo tiene una entrada.
"""
id = "d133a53d-535d-491e-a7f8-09e7bb62e1b0"


[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Dentro del TAD Diccionario que hemos implementado en la clase `MapTree`, Â¿en quÃ© se diferencian los mÃ©todos de bÃºsqueda `at` y `operator[]`?
"""
prompt.distractors = [
	"En el tipo del valor devuelto. En un caso se devuelve una clave; en otro un booleano.",
	"En el coste en el caso peor"
]

answer.answer = "En la forma en la que se comportan cuando la clave a buscar no estÃ¡ en el diccionario"
id = "a4c2585c-012c-4898-af1e-b5238c0d1cf0"


[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Supongamos un diccionario de *n* entradas implementado mediante un Ã¡rbol binario de bÃºsqueda equilibrado. Â¿CuÃ¡l es el coste, en el caso peor, de la operaciÃ³n `at`?
"""
prompt.distractors = [
"""
<math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mi>n</mi><mo form="postfix" stretchy="false">)</mo></mrow></math>
""",
"""
<math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mn>1</mn><mo form="postfix" stretchy="false">)</mo></mrow></math>
"""	
]

answer.answer = """
<math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mrow><mi>log</mi><mo>â¡</mo><mspace width="0.1667em"></mspace></mrow><mi>n</mi><mo form="postfix" stretchy="false">)</mo></mrow></math>
"""
id = "f85270b4-2fdd-48a0-826f-13ace3758b38"



[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Supongamos un diccionario de *n* entradas implementado mediante un Ã¡rbol binario de bÃºsqueda equilibrado. Â¿CuÃ¡l es el coste, en el caso peor, de la operaciÃ³n `erase`?
"""
prompt.distractors = [
"""
<math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mi>n</mi><mo form="postfix" stretchy="false">)</mo></mrow></math>
""",
"""
<math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mn>1</mn><mo form="postfix" stretchy="false">)</mo></mrow></math>
"""	
]

answer.answer = """
<math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mrow><mi>log</mi><mo>â¡</mo><mspace width="0.1667em"></mspace></mrow><mi>n</mi><mo form="postfix" stretchy="false">)</mo></mrow></math>
"""
id = "cfbd24eb-73c3-4ee1-8352-b6b3c5f4d271"



[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Supongamos un diccionario de *n* entradas implementado mediante un Ã¡rbol binario de bÃºsqueda, pero no sabemos si este Ã¡rbol estÃ¡ equilibrado o no. Â¿CuÃ¡l es el coste, en el caso peor, de la operaciÃ³n `contains`?
"""
prompt.distractors = [
"""
<math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mrow><mi>log</mi><mo>â¡</mo><mspace width="0.1667em"></mspace></mrow><mi>n</mi><mo form="postfix" stretchy="false">)</mo></mrow></math>
""",
"""
<math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mn>1</mn><mo form="postfix" stretchy="false">)</mo></mrow></math>
"""	
]

answer.answer = """
<math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mi>n</mi><mo form="postfix" stretchy="false">)</mo></mrow></math>
"""
id = "4368fd80-b197-4b65-9cba-cfed68a23886"


[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Supongamos un diccionario de *n* entradas implementado mediante un Ã¡rbol binario de bÃºsqueda equilibrado. Â¿CuÃ¡l es el coste, en el caso peor, de la operaciÃ³n `insert`?
"""
prompt.distractors = [
"""
<math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mi>n</mi><mo form="postfix" stretchy="false">)</mo></mrow></math>
""",
"""
<math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mn>1</mn><mo form="postfix" stretchy="false">)</mo></mrow></math>
"""	
]

answer.answer = """
<math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mrow><mi>log</mi><mo>â¡</mo><mspace width="0.1667em"></mspace></mrow><mi>n</mi><mo form="postfix" stretchy="false">)</mo></mrow></math>
"""
id = "94534f8f-c4a4-45d6-b8fc-415ccdb64f44"



[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Supongamos un diccionario de *n* entradas implementado mediante un Ã¡rbol binario de bÃºsqueda. Â¿CuÃ¡l es el coste, en el caso peor, de la operaciÃ³n `size`?
"""
prompt.distractors = [
"""
<math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mrow><mi>log</mi><mo>â¡</mo><mspace width="0.1667em"></mspace></mrow><mi>n</mi><mo form="postfix" stretchy="false">)</mo></mrow></math> si el Ã¡rbol estÃ¡ equilibrado; <math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mi>n</mi><mo form="postfix" stretchy="false">)</mo></mrow></math> si es un Ã¡rbol degenerado
""",
"""
<math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mn>1</mn><mo form="postfix" stretchy="false">)</mo></mrow></math> si es un Ã¡rbol equilibrado, <math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mi>n</mi><mo form="postfix" stretchy="false">)</mo></mrow></math> si es un Ã¡rbol degenerado
"""	
]

answer.answer = """
<math><mrow><mi class="mathcal">ğ’ª</mi><mo form="prefix" stretchy="false">(</mo><mn>1</mn><mo form="postfix" stretchy="false">)</mo></mrow></math> en cualquier caso
"""
id = "fd52b032-078d-44fa-8416-0b3ebbdd772f"



